### ISSUE TITLE
Cameras?

### ISSUE THREAD

**Issue by JetForMe** [openpnp/openpnp-openbuilds#6]
Hi. In the BOM I see the "head camera," but I don't see the other camera (the one it holds parts over for identification and positioning). Is it a second of the same camera and lens?

Thanks.

**Comment by vonnieda** [comment]
Hi @JetForMe, the current stable build (the master branch) does not include the bottom vision camera. I have not yet done an official release of the version of the machine that includes it since several other parts have changed. Here's the current status of things:

Develop Branch:
- Z plate size increased to accommodate taller nozzle adapters.
- Z home switch removed, homing is done by by the springs now.
- Juki nozzle adapters and nozzles added.
- Bottom vision camera added.
- Hardware shown at Maker Faire 2016.
- BOM has not been updated yet.

Master Branch:
- Current stable release.
- Shown at Maker Faire 2015.

The primary change between the two is the change from Fuji CP-6 nozzles to Juki nozzles. This required a change to the Z plate, moving everything up. I have not yet decided if I feel like this is good enough for release, and the parts are more difficult to source, so I haven't made it official yet. The biggest issue is that the Juki nozzle adapters I am using were custom made. There is a community member who has just sourced a version of these, so if they prove to be compatible I will recommend those as the source and update the Develop branch to the Master branch.

**Comment by JetForMe** [comment]
Oh, interesting. How do you properly rotate parts without the bottom camera?

**Comment by JetForMe** [comment]
Also, sorry. What camera is used for the bottom? I don't see a BOM in the github repo, just on Google drive. Same camera/lens as the head?

**Comment by vonnieda** [comment]
Rotation is just handled blindly. It works well for 0805s and above, and 0.8mm pitch ICs and above. As you get smaller you really need the bottom vision to improve accuracy.

The camera is the same camera, different lens. I believe I'm using a 3.2mm fisheye at the moment. I can't quite tell because it's inside the box, but I will check next time I take the lid off.

It has a lot to do with how you build the frame and where you mount the camera. It's just a matter of being able to get the part above the camera and in focus.

When I release the new version I'll archive the current BOM and update it with the new parts, including the camera and lens. Aside from that the only other change to the BOM is the use of a different, quieter vacuum pump. I'm using this one now: http://www.robotdigg.com/product/599/Diaphragm+pump+4+desktop+PNP+Machine

**Comment by JetForMe** [comment]
Awesome, thanks!
